/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package pe.com.intercorp.bean;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-23T12:15:54.600-05:00[America/Bogota]")
@Api(value = "creacliente", description = "the creacliente API")
public interface CreaclienteApi {

    @ApiOperation(value = "Funcionalidad para [REGISTRAR] una ENTIDAD de tipo Customer.", nickname = "creacliente", notes = "Funcionalidad para [REGISTRAR] una ENTIDAD de tipo Customer.", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PROCESO EXITOSO", response = String.class),
        @ApiResponse(code = 400, message = "ERROR EN EL PROCESO", response = String.class) })
    @RequestMapping(value = "/creacliente",
        produces = { "application/json" }, 
        consumes = { "*/*" },
        method = RequestMethod.POST)
    ResponseEntity<String> creacliente(@ApiParam(value = "La Entidad del Customer" ,required=true )  @Valid @RequestBody Customer body);

}
